CREATE TABLE IF NOT EXISTS tags
(
    id   SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS articles_tags
(
    article_id INTEGER NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
    tag_id     INTEGER NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
    PRIMARY KEY (article_id, tag_id)
);
